import Head from "next/head";
import Connecet from "../components/Connecet";
import Main from "../components/Main";
import Sidebar from "../components/Sidebar";
import styles from "../styles/Home.module.css";
import { ContextWrapper } from "../Context";
import { ethers } from "ethers";

import { useProvider } from "wagmi";

// rainbowkit
import "@rainbow-me/rainbowkit/styles.css";
import { getDefaultWallets, RainbowKitProvider } from "@rainbow-me/rainbowkit";
import { chain, configureChains, createClient, WagmiConfig } from "wagmi";
import { alchemyProvider } from "wagmi/providers/alchemy";
import { publicProvider } from "wagmi/providers/public";

//Interacting with smart contract
import { useAccount, usePrepareContractWrite, useContractWrite } from 'wagmi'


const { chains, provider } = configureChains(
  [chain.mainnet, chain.polygon, chain.optimism, chain.arbitrum],
  [alchemyProvider({ apiKey: process.env.ALCHEMY_ID }), publicProvider()]
);
const { connectors } = getDefaultWallets({
  appName: "My RainbowKit App",
  chains,
});
const wagmiClient = createClient({
  autoConnect: true,
  connectors,
  provider,
});


export default function Home() {

  return (
    <WagmiConfig client={wagmiClient}>
      <RainbowKitProvider chains={chains}>
        <ContextWrapper>
          <div className={styles.container}>
            <Head>
              <title>BinancePay</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex gap-6">
              <Sidebar />
              <div className="w-full pr-6 pt-4">
                <Connecet />
                <Main />
              </div>
            </div>
          </div>
        </ContextWrapper>
      </RainbowKitProvider>
    </WagmiConfig>
  );
}
